const data = {
  products: [
    {
      name: "Modern Soul",
      slug: "Modern Soul",
      category: "T-Shirts",
      image: "/images/p1.jpg",
      price: 399,
      countInStock: 10,
      brand: "Modern Soul",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Denim",
      slug: "Denim-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 850,
      countInStock: 20,
      brand: "Denim",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Under Armour",
      slug: "Under Armour T-Shirt",
      category: "T-Shirt",
      image: "/images/p3.jpg",
      price: 500,
      countInStock: 15,
      brand: "Under Armour",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Under Armour",
      slug: "Under Armour Shoes",
      category: "Shoes",
      image: "/images/p4.jpg",
      price: 1299,
      countInStock: 5,
      brand: "Under Armour",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
